name: Unused dependencies

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  machete:
    name: cargo-machete
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-machete
      - run: cargo machete

  udeps:
    name: cargo-udeps (nightly)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-udeps
      - run: cargo +nightly udeps --all-targets
